### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by FranzSkuffka** [markcellus/content-editable#97]
please :)

**Comment by mkay581** [comment]
Oh this package is in its earliest stages so a full demo would be a little while. But I can throw up a gif animation in the meantime. Would that be ok?

**Comment by FranzSkuffka** [comment]
Sure that would be great! Can you make sure the inspector is also visible in the gif?

**Comment by markcellus** [comment]
@FranzSkuffka I've made the component "demoable" by pulling down locally and running `npm start`. :+1:
